/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'DevilMayCry5.exe'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct via::uvar::Data1;

/* 371 */
struct via::uvar::Header
{
  uint32_t Version;
  char ID[4];
  uint64_t addrOfs_8h;
  uint64_t addrOfs_10h;
  uint64_t addrOfs_18h;
  uint64_t addrOfs_20h;
  uint64_t addrOfs_28h;
  uint32_t uint32_30h;
  uint16_t count_34h;
  uint16_t count_36h;
  uint64_t addrOfs_38h;
};

/* 369 */
struct via::uvar::UvarData
{
  via::uvar::Header header;
  via::uvar::Data1 *pDataArr;
};

/* 372 */
struct via::uvar::Data1
{
  uint64_t addrOfs_0h;
  uint64_t addrOfs_8h;
  uint64_t addrOfs_10h;
  uint64_t addrOfs_18h;
  uint64_t addrOfs_20h;
  uint64_t addrOfs_28h;
};

